include_guard(GLOBAL)

# ============================================================================
# cmake/git.cmake —— 采集构建溯源信息，生成 xplugin_build_info_generated.h
#
# 范式来源：xvm/cmake/git.cmake（xvm 又从 PEL 适配）。为 xplugin 再适配：
#   - 无 git / 非仓库：所有 git 调用优雅降级为 "nogit"，绝不 FATAL。
#   - 生成头写入构建目录（${CMAKE_BINARY_DIR}/generated/），不污染源码树、不入库。
#   - 函数式接口 xpl_generate_build_info(<out_header_var>)。
#
# 采集内容为“构建溯源”（provenance）：git commit/branch、时间戳、主机、系统、工具链。
# 与语义版本 XPLUGIN_VERSION_*（xplugin.h）互补、不重复。
# 刷新：git 信息在 configure 时采集；换 commit 后重跑 cmake 即更新。
# ============================================================================

function(xpl_generate_build_info out_header_var)
    # ---- git commit（无 git / 非仓库 → nogit）----
    set(_git_commit "nogit")
    set(_git_branch "nogit")
    find_program(_GIT_EXECUTABLE git)
    if (_GIT_EXECUTABLE)
        execute_process(
            COMMAND ${_GIT_EXECUTABLE} rev-parse HEAD
            WORKING_DIRECTORY ${XPLUGIN_PROJECT_ROOT}
            OUTPUT_VARIABLE _commit_raw
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
            RESULT_VARIABLE _commit_rc
        )
        if (_commit_rc EQUAL 0 AND NOT "${_commit_raw}" STREQUAL "")
            # dirty 检测
            execute_process(
                COMMAND ${_GIT_EXECUTABLE} status --porcelain
                WORKING_DIRECTORY ${XPLUGIN_PROJECT_ROOT}
                OUTPUT_VARIABLE _status_raw
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
            )
            if ("${_status_raw}" STREQUAL "")
                set(_git_commit "${_commit_raw}")
            else ()
                set(_git_commit "${_commit_raw}-dirty")
            endif ()

            execute_process(
                COMMAND ${_GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD
                WORKING_DIRECTORY ${XPLUGIN_PROJECT_ROOT}
                OUTPUT_VARIABLE _branch_raw
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
                RESULT_VARIABLE _branch_rc
            )
            if (_branch_rc EQUAL 0 AND NOT "${_branch_raw}" STREQUAL "")
                set(_git_branch "${_branch_raw}")
            endif ()
        endif ()
    endif ()

    # ---- 时间戳 / 主机 / 系统 / 工具链 ----
    string(TIMESTAMP _timestamp "%Y-%m-%dT%H:%M:%S")

    set(_host "unknown")
    execute_process(COMMAND hostname
        OUTPUT_VARIABLE _host_raw OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _host_rc)
    if (_host_rc EQUAL 0 AND NOT "${_host_raw}" STREQUAL "")
        set(_host "${_host_raw}")
    elseif (NOT "$ENV{HOSTNAME}" STREQUAL "")
        set(_host "$ENV{HOSTNAME}")
    endif ()

    set(_system "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
    set(_compiler "${CMAKE_C_COMPILER_ID}-${CMAKE_C_COMPILER_VERSION}")

    # ---- 转义（防注入换行/引号）----
    foreach (_v _git_commit _git_branch _timestamp _host _system _compiler)
        string(REPLACE "\\" "\\\\" ${_v} "${${_v}}")
        string(REPLACE "\"" "\\\"" ${_v} "${${_v}}")
        string(REPLACE "\n" " " ${_v} "${${_v}}")
    endforeach ()

    # ---- 生成头（构建目录内）----
    set(_gen_dir "${CMAKE_BINARY_DIR}/generated/xplugin")
    set(_gen_header "${_gen_dir}/xplugin_build_info_generated.h")
    file(MAKE_DIRECTORY "${_gen_dir}")
    file(WRITE  "${_gen_header}" "/* auto-generated by cmake/git.cmake — do not edit, not tracked */\n")
    file(APPEND "${_gen_header}" "#ifndef XPLUGIN_BUILD_INFO_GENERATED_H\n#define XPLUGIN_BUILD_INFO_GENERATED_H\n\n")
    file(APPEND "${_gen_header}" "#define XPL_BUILD_GIT_COMMIT \"${_git_commit}\"\n")
    file(APPEND "${_gen_header}" "#define XPL_BUILD_GIT_BRANCH \"${_git_branch}\"\n")
    file(APPEND "${_gen_header}" "#define XPL_BUILD_TIMESTAMP \"${_timestamp}\"\n")
    file(APPEND "${_gen_header}" "#define XPL_BUILD_HOST     \"${_host}\"\n")
    file(APPEND "${_gen_header}" "#define XPL_BUILD_SYSTEM   \"${_system}\"\n")
    file(APPEND "${_gen_header}" "#define XPL_BUILD_COMPILER \"${_compiler}\"\n\n")
    file(APPEND "${_gen_header}" "#endif /* XPLUGIN_BUILD_INFO_GENERATED_H */\n")

    message(STATUS "build-info: commit=${_git_commit} branch=${_git_branch} @ ${_timestamp}")
    set(${out_header_var} "${_gen_header}" PARENT_SCOPE)
endfunction()
