include_guard(GLOBAL)

# Sanitizer 接线（对齐 xvm/cmake/sanitizer.cmake）
# 纪律：回归测试与整体测试 TSan + ASan 打底（分两趟跑，二者互斥）

option(SAN_ADDRESS "Enable Address Sanitizer (Linux GCC/Clang; Windows MSVC VS2019 16.9+)" OFF)
option(SAN_THREAD  "Enable Thread Sanitizer (Linux/macOS; Windows 无 TSan)" OFF)
option(SAN_UB      "Enable Undefined Behavior Sanitizer" OFF)

set(XPLUGIN_SANITIZER_ACTIVE OFF)

if (SAN_ADDRESS AND SAN_THREAD)
    message(WARNING "ASan and TSan are mutually exclusive. Disabling TSan. (跑两趟：一趟 ASan，一趟 TSan)")
    set(SAN_THREAD OFF)
endif ()

if (SAN_THREAD AND SAN_UB)
    message(WARNING "TSan and UBSan may interact; disabling UBSan for TSan run.")
    set(SAN_UB OFF)
endif ()

if (SAN_ADDRESS)
    if (MSVC)
        if (MSVC_VERSION LESS 1928)
            message(WARNING "MSVC ASan needs VS2019 16.9+ (_MSC_VER >= 1928), got ${MSVC_VERSION}. SAN_ADDRESS forced OFF.")
            set(SAN_ADDRESS OFF)
        else ()
            message(STATUS "=== ASan enabled (MSVC /fsanitize=address) ===")
            string(REPLACE "/RTC1" "" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
            string(REPLACE "/RTCsu" "" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
            add_compile_options("/fsanitize=address")
            add_link_options("/INCREMENTAL:NO")
            set(XPLUGIN_SANITIZER_ACTIVE ON)
        endif ()
    elseif (APPLE)
        message(WARNING "ASan disabled on macOS. SAN_ADDRESS forced OFF.")
        set(SAN_ADDRESS OFF)
    else ()
        message(STATUS "=== ASan enabled (Linux) ===")
        add_compile_options("-fsanitize=address" "-fsanitize-address-use-after-scope")
        add_link_options("-fsanitize=address" "-fsanitize-address-use-after-scope")
        if (SAN_UB)
            add_compile_options("-fsanitize=undefined" "-fno-sanitize-recover=undefined")
            add_link_options("-fsanitize=undefined")
            message(STATUS "  UBSan: combined with ASan")
            set(SAN_UB OFF)
        endif ()
        set(XPLUGIN_SANITIZER_ACTIVE ON)
    endif ()
endif ()

if (SAN_THREAD)
    if (WIN32)
        message(WARNING "TSan disabled on Windows. SAN_THREAD forced OFF.")
        set(SAN_THREAD OFF)
    else ()
        message(STATUS "=== TSan enabled ===")
        add_compile_options("-fsanitize=thread")
        add_link_options("-fsanitize=thread")
        set(XPLUGIN_SANITIZER_ACTIVE ON)
    endif ()
endif ()

if (SAN_UB)
    message(STATUS "=== UBSan enabled ===")
    add_compile_options("-fsanitize=undefined" "-fno-sanitize-recover=undefined")
    add_link_options("-fsanitize=undefined")
    set(XPLUGIN_SANITIZER_ACTIVE ON)
endif ()

if (XPLUGIN_SANITIZER_ACTIVE)
    add_compile_definitions(XPLUGIN_SANITIZER_ENABLED=1)
endif ()
